config/routes.rb
Rails.application.routes.draw do
  root "incidents#index"

  resources :found_animals, except: [:destroy]
  resources :lost_animals
  resources :users
  resources :incidents
  
  get '/login', to: 'session#new'
  delete 'incidents/:id', to: 'incidents#destroy'
  post 'session', to: 'session#create'
  delete 'session', to: 'session#destroy'
  get 'users/profile/:id', to: 'users#profile'

  namespace 'api' do
    resources :found_animals
    resources :lost_animals
    resources :users
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/lost_animal.rb
class LostAnimal < ApplicationRecord
  validates :species, :date_lost, :location_lost , :incident_id, :user_id, :lat, :long, presence: true
  belongs_to :incident
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/controllers/api/lost_animals_controller.rb
class Api::LostAnimalsController < ApplicationController
    protect_from_forgery with: :null_session
    def index
        @lost_animals = LostAnimal.order('created_at DESC')
        render json: { status: 'Success', message: 'Animals lost', data: @lost_animals }, status: :ok
    end 

    def show
        lost_animal = FoundAnimal.find(params[:id])
        render json: { status: 'Success', message: 'Animal found', data: lost_animal }, status: :ok
    end 
end 

app/controllers/lost_animals_controller.rb
class LostAnimalsController < ApplicationController
  def index
    if params[:incident]
      @lost_animals = LostAnimal.where("incident_id = ?", params[:incident].to_i)
      @lost_map_data = {
        lat: @lost_animals.pluck(:lat), 
        long: @lost_animals.pluck(:long), 
        location: @lost_animals.pluck(:location_lost),
      }
    else
      @lost_animals = LostAnimal.all
      @lost_map_data = {
        lat: @lost_animals.pluck(:lat), 
        long: @lost_animals.pluck(:long), 
        location: @lost_animals.pluck(:location_lost)
      }
    end
  end
  
  def new
    @incidents = Incident.all
    @health_status = Animal::HEALTH
    @species = Animal::SPECIES
    #@user = session.user
  end

  def create
    if User.find_by(id: session[:user_id]) == nil
      redirect_to '/login'
    else
      @user = User.find_by(id: session[:user_id])
      animal = LostAnimal.new
      animal.species = params[:species]
      animal.date_lost = params[:date_lost]
      animal.location_lost = params[:location_lost]
      animal.lat = Geocoder.coordinates(animal.location_lost).first
      animal.long = Geocoder.coordinates(animal.location_lost).last
      animal.image = params[:image]
      animal.incident_id = params[:incident_id]
      animal.user_id = @user.id
      animal.tags = params[:tags].split(' ')
      animal.tags.unshift(animal.species)
      animal.tags.unshift(animal.location_lost)
      animal.tags = animal.tags.uniq
      animal.reunited = false
      animal.tags.map! do |tag|
        tag.downcase
      end
      animal.save
      redirect_to(lost_animals_path)
    end
  end
  

  def show
    @animal = LostAnimal.find(params[:id])
  end

  def edit
    @animal = LostAnimal.find(params[:id])
    @incidents = Incident.all
    @animal_species = Animal::SPECIES
  end
  
  def update
    animal = LostAnimal.find(params[:id])
    animal.species = params[:species]
    animal.date_lost = params[:date_lost]
    animal.image = params[:image]
    animal.location_lost = params[:location_lost]
    animal.lat = Geocoder.coordinates(animal.location_lost).first
    animal.long = Geocoder.coordinates(animal.location_lost).last
    animal.incident_id = params[:incident_id]
    animal.tags = params[:tags].split(' ')
    animal.tags.unshift(animal.species)
    animal.tags.unshift(animal.location_lost)
    animal.tags = animal.tags.uniq
    animal.tags.map! do |tag|
      tag.downcase
    end
    animal.reunited = params[:reunited]
    if animal.save
      redirect_to(lost_animal_path(animal))
    else
      render :edit
    end
  end
  
end

app/helpers/lost_animals_helper.rb
module LostAnimalsHelper
end

app/views/lost_animals/_form.html.erb
<%= form_for @animal, html: { multipart: true } do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :species %><br>
    <%= f.text_area :species %>
  </div>
    <div class="field">
    <%= f.label :date_lost %><br>
    <%= f.text_area :date_lost %>
  </div>
    <div class="field">
    <%= f.label :location_lost %><br>
    <%= f.text_area :location_lost %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lost_animals/edit.html.erb
<h2 class="page-title">Edit your  animals details</h2>
<h5 class="sub-title">Please update the animals details below.</h5>

<div class="form-container">
  <%= form_tag lost_animal_path(@animal), multipart: true, method: :put do %>
    <div class="form">
      <label for="">Incident<span>*</span></label>
      <select name="incident_id" id="">
        <% @incidents.each do |incident| %>
          <% if @animal.incident.id === incident.id  %>
            <option value="<%= incident.id %>" selected><%= incident.name %></option>
          <% else %>
            <option value="<%= incident.id %>"><%= incident.name %></option>
          <% end %>
        <% end %>
      </select>
      <label for="">Species<span>*</span></label>
      <select name="species" id="">
        <% @animal_species.each do |species| %>
          <% if @animal.species === species %>
            <option value="<%= species %>"><%= species.capitalize %></option>
          <% else %>  
            <option value="<% species %>"><%= species.capitalize %></option>
          <% end %>
        <% end  %>
      </select>
      <label for="">Date Animal was lost<span>*</span></label>
      <input type="date" name="date_lost" value="<%= @animal.date_lost %>" class="datefield" required>
      <label for="">Location of the Animal lost<span>*</span></label>
      <input type="text" name="location_lost" value="<%= @animal.location_lost %>" required>
      <label for="">Image of Animal</label>
      <input type="file" name="image">
      <label for="">Please enter single word tags</label>
        <textarea name="tags" value="tags"><%= @animal.tags.join(' ') %></textarea>
      <label for="">Reunited?</label>
      <select name="reunited" id="">
        <% if @animal.reunited === false %>
          <option value="false" selected>No</option>
          <option value="true">Yes</option>
        <% end %>
      </select>
      <p>* Required Fields</p>
      <button>Edit Animal</button>
    </div>
  <% end %>
</div>

app/views/lost_animals/index.html.erb
<h2 class="page-title">Lost Animals</h2>

<div class="search-bar">
  <form action="" class="search-form">
    <input type="text" class="search-input">
    <button>Search</button>
  </form>
</div>

<div class="map-wrapper">
  <div id="mapContainer"></div>
</div>

<div id="lost-animal-data" data-animals="<%= @lost_map_data.to_json %>"></div>

<div class="results-container">
  <% @lost_animals.each do |animal| %>
    <div class="animal-item" onclick="location.href='<%= lost_animal_path(animal)%>'">
      <p class="tags"><%= animal.tags.join(' // ') %></p>
      <div class="item-header">
        <h3><%= animal.species.capitalize %> lost in <%= animal.location_lost %></h3>
      </div>
      <div class="item-content">
        <img src="<%= animal.image %>" alt="Lost <%= animal.species %>">
        <h4>Lost at: <span><%= animal.location_lost %></span></h4>
        <h4>Date lost: <span><%= animal.date_lost.strftime("%a, %d-%h-%G") %></span></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/lost_animals/new.html.erb
<h2 class="page-title">Have you lost an Animal?</h2>
<h5 class="sub-title">Please enter the animals details below.</h5>

<div class="form-container">
  <%= form_tag lost_animals_path, multipart: true, method: :post do %>
    <div class="form">
      <label for="">Incident<span>*</span></label>
      <select name="incident_id" id="">
        <% @incidents.each do |incident| %>
          <option value="<%= incident.id %>"><%= incident.name %></option>
        <% end %>
      </select>
      <label for="">Species<span>*</span></label>
      <select name="species" id="">
        <% @species.each do |species| %>
          <option value="<%= species %>"><%= species.capitalize() %></option>
        <% end %>
      </select>
      <label for="">Date Animal was lost<span>*</span></label>
      <input type="date" class="datefield" name="date_lost" required>
      <label for="">Location Animal was lost (please include the city)<span>*</span></label>
      <input type="text" name="location_lost" required>
      <label for="">Please upload image of animal</label>
      <input type="file" name="image">
      <label for="">Please enter single word tags</label>
      <textarea name="tags"></textarea>
      <p>* Required Fields</p>
      <button>Add Animal</button>
    </div>
  <% end %>
</div>

app/views/lost_animals/show.html.erb
<h2 class="page-title">Lost Animal</h2>

<div class="show-container">
  <div class="show-header">
    <h3><%= @animal.species.capitalize %> lost during the <%= @animal.incident.name %> incident</h3>
  </div>
  <div class="show-content">
    <% if @animal.reunited === false %>
      <h4> Animal hasn't been reunited yet</h4>
    <% end %>
    <img src="<%= @animal.image.url %>" alt="">
    <h3>Location lost <span><%= @animal.location_lost %></span></h3>
    <p class="lat"><%= @animal.lat %></p>
    <p class="long"><%= @animal.long %></p>
    <h3 id="user_location"></h3>
    <h3>Date lost: <span><%= @animal.date_lost %></span></h3>
    <%= link_to "Contact #{@animal.user.name}", "/users/profile/#{@animal.user.id}", class: 'link-btn show' %>
    <% if @animal.user.id == session[:user_id] %>
    <a href="<%= edit_lost_animal_path(@animal) %>" class="link-btn show">Edit Animal</a>
    <% end %>
  </div>
</div>