config/routes.rb
Rails.application.routes.draw do
  root "incidents#index"

  resources :found_animals, except: [:destroy]
  resources :lost_animals
  resources :users
  resources :incidents
  
  get '/login', to: 'session#new'
  delete 'incidents/:id', to: 'incidents#destroy'
  post 'session', to: 'session#create'
  delete 'session', to: 'session#destroy'
  get 'users/profile/:id', to: 'users#profile'

  namespace 'api' do
    resources :found_animals
    resources :lost_animals
    resources :users
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/found_animal.rb
class FoundAnimal < ApplicationRecord
  validates :species, :date_found, :location_found, :location_current, :incident_id, :user_id, :lat, :long, presence: true
  belongs_to :incident
  belongs_to :user

  mount_uploader :image, ImageUploader
end

app/controllers/api/found_animals_controller.rb
class Api::FoundAnimalsController < ApplicationController
    protect_from_forgery with: :null_session
    def index
        @found_animals = FoundAnimal.order('created_at DESC')
        render json: { status: 'Success', message: 'Animals found', data: @found_animals }, status: :ok
    end 

    def show
        found_animal = FoundAnimal.find(params[:id])
        render json: { status: 'Success', message: 'Animal found', data: found_animal }, status: :ok
    end 
end 

app/controllers/found_animals_controller.rb
class FoundAnimalsController < ApplicationController
  def index
    if params[:incident]
      @found_animals = FoundAnimal.where("incident_id = ?", params[:incident].to_i)
      @found_map_data = {
        lat: @found_animals.pluck(:lat), 
        long: @found_animals.pluck(:long), 
        location: @found_animals.pluck(:location_current)
      }
    else
      @found_animals = FoundAnimal.all
      @found_map_data = {
        lat: @found_animals.pluck(:lat), 
        long: @found_animals.pluck(:long), 
        location: @found_animals.pluck(:location_current)
      }
    end
  end

  def show
    @animal = FoundAnimal.find(params[:id])
  end

  def new
    @incidents = Incident.all
    @health_status = Animal::HEALTH
    @species = Animal::SPECIES
    #@user = session.user
  end

  def create
    if User.find_by(id: session[:user_id]) == nil
      redirect_to '/login'

    else
      @user = User.find_by(id: session[:user_id])
      animal = FoundAnimal.new
      animal.species = params[:species]
      animal.date_found = params[:date_found]
      animal.location_found = params[:location_found]
      animal.location_current = params[:location_current]
      animal.lat = Geocoder.coordinates(animal.location_current).first
      animal.long = Geocoder.coordinates(animal.location_current).last
      animal.image = params[:image]
      animal.health_status = params[:health_status]
      animal.incident_id = params[:incident_id]
      animal.user_id = @user.id
      animal.tags = params[:tags].split(' ')
      animal.tags.unshift(animal.species)
      animal.tags.unshift(animal.health_status)
      animal.tags.unshift(animal.location_found)
      animal.tags = animal.tags.uniq
      animal.tags.map! do |tag|
        tag.downcase
      end
      animal.reunited = false
      animal.save
      redirect_to(found_animal_path(animal.id))
    end
  end

  def edit
    @animal = FoundAnimal.find(params[:id])
    @incidents = Incident.all
    @animal_species = Animal::SPECIES
    @health_status = Animal::HEALTH
  end

  def update
    animal = FoundAnimal.find(params[:id])
    animal.species = params[:species]
    animal.date_found = params[:date_found]
    animal.location_found = params[:location_found]
    animal.location_current = params[:location_current]
    animal.lat = Geocoder.coordinates(params[:location_current]).first
    animal.long = Geocoder.coordinates(params[:location_current]).last
    animal.image = params[:image]
    animal.health_status = params[:health_status]
    animal.incident_id = params[:incident_id]
    animal.tags = params[:tags].split(' ')
    animal.tags.unshift(animal.species)
    animal.tags.unshift(animal.health_status)
    animal.tags.unshift(animal.location_found)
    animal.tags = animal.tags.uniq
    animal.tags.map! do |tag|
      tag.downcase
    end
    animal.reunited = params[:reunited]
    if animal.save
      redirect_to(found_animal_path(animal))
    else
      render :edit
    end
  end


end

app/helpers/found_animals_helper.rb
module FoundAnimalsHelper
end

app/views/found_animals/_form.html.erb
<%= form_for @pet, html: { multipart: true } do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/found_animals/edit.html.erb
<h2 class="page-title">Edit your animals details</h2>
<h5 class="sub-title">Please update the animals details below.</h5>
<div class="form-container">
  <%= form_tag found_animal_path(@animal), multipart: true, method: :put do %>
    <div class="form">
      <label for="">Incident<span>*</span></label>
      <select name="incident_id" id="">
        <% @incidents.each do |incident| %>
          <% if @animal.incident.id === incident.id  %>
            <option value="<%= incident.id %>" selected><%= incident.name %></option>
          <% else %>
            <option value="<%= incident.id %>"><%= incident.name %></option>
          <% end %>
        <% end %>
      </select>
      <label for="">Species<span>*</span></label>
      <select name="species" id="">
        <% @animal_species.each do |species| %>
          <% if @animal.species === species %>
            <option value="<%= species %>"><%= species.capitalize %></option>
          <% else %>  
            <option value="<% species %>"><%= species.capitalize %></option>
          <% end %>
        <% end  %>
      </select>
      <label for="">Date Animal was Found<span>*</span></label>
      <input type="date" name="date_found" value="<%= @animal.date_found %>" class="datefield" required>
      <label for="">Location Animal was Found<span>*</span></label>
      <input type="text" name="location_found" value="<%= @animal.location_found %>" required>
      <label for="">Current Location of Animal<span>*</span></label>
      <input type="text" name="location_current" value="<%= @animal.location_current %>" required>
      <label for="">Image of Animal</label>
      <input type="file" name="image">
      <label for="">Health Status</label>
      <select name="health_status" id="">
        <% @health_status.each do |status| %>
          <% if @animal.health_status === status %>
            <option value="<%= status %>" selected><%= status.capitalize %></option>
          <% else %>
            <option value="<%= status %>"><%= status.capitalize %></option>
          <% end  %>
        <% end  %>
      </select>
      <label for="">Please enter single word tags</label>
      <textarea name="tags" value="tags"><%= @animal.tags.join(' ') %></textarea>
      <label for="">Reunited?</label>
      <select name="reunited" id="">
        <% if @animal.reunited === false %>
          <option value="false" selected >No</option>
        <% end %>
          <option value="true">Yes</option>
      </select>
      <p>* Required Fields</p>
      <button>Edit Animal</button>
    </div>
  <% end %>
</div>

app/views/found_animals/index.html.erb
<h2 class="page-title">Found Animals</h2>

<div class="search-bar">
  <form action="" class="search-form">
    <input type="text" class="search-input">
    <button>Search</button>
  </form>
</div>

<div class="map-wrapper">
  <div id="mapContainer"></div>
</div>

<div id="found-animal-data" data-animals="<%= @found_map_data.to_json %>"></div>

<div class="results-container">
  <% @found_animals.each do |animal| %>
    <div class="animal-item" onclick="location.href='<%= found_animal_path(animal)%>'">
      <p class="tags"><%= animal.tags.join(' // ') %></p>
      <div class="item-header">
        <h3><%= animal.species.capitalize %> found in <%= animal.location_found %></h3>
      </div>
      <div class="item-content">
        <img src="<%= animal.image %>" alt="Lost <%= animal.species %>">
        <h4>Currently at: <span><%= animal.location_current %></span></h4>
        <h4>Date Found: <span><%= animal.date_found.strftime("%a, %d-%h-%G") %></span></h4>
        <h4>Date Posted: <span><%= animal.created_at.strftime("%a, %d-%h-%G") %></span></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/found_animals/new.html.erb
<h2 class="page-title">Have you found an Animal?</h2>
<h5 class="sub-title">Please enter the animals details below.</h5>

<div class="form-container">
  <%= form_tag found_animals_path, multipart: true, method: :post do %>
    <div class="form">
      <label for="">Incident<span>*</span></label>
      <select name="incident_id" id="" required>
        <option value="" disabled selected>Please Select An Incident</option>
        <% @incidents.each do |incident| %>
          <option value="<%= incident.id %>"><%= incident.name %></option>
        <% end %>
      </select>
      <label for="">Species<span>*</span></label>
      <select name="species" id="" required>
        <option value="" disabled selected>Please Select A Species</option>
        <% @species.each do |species| %>
          <option value="<%= species %>" ><%= species.capitalize() %></option>
        <% end %>
      </select>
      <label for="">Date Animal was Found<span>*</span></label>
      <input type="date" name="date_found" class="datefield" required>
      <label for="">Location Animal was Found<span>*</span></label>
      <input type="text" name="location_found" required>
      <label for="">Current Location of Animal (please include the city)<span>*</span></label>
      <input type="text" name="location_current" required>
      <label for="">Please upload an image of the animal</label>
      <input type="file" name="image">
      <label for="">Health Status<span>*</span></label>
      <select name="health_status" id="" required>
        <option value="" selected disabled>Please Select Health Status</option>
        <% @health_status.each do |status| %>
          <option value="<%= status %>"><%= status.capitalize() %></option>
        <% end %>
      </select>
      <label for="">Please enter single word tags</label>
      <textarea name="tags"></textarea>
      <p>* Required Fields</p>
      <button>Add Animal</button>
    </div>
  <% end %>
</div>

app/views/found_animals/show.html.erb
<div class="show-container">
  <div class="show-header">
    <h3><%= @animal.species.capitalize %> found during the <%= @animal.incident.name %> incident</h3>
  </div>
  <div class="show-content">
    <% if @animal.reunited === false %>
      <h4> Animal hasn't been reunited yet</h4>
    <% end %>
    <img src="<%= @animal.image.url %>" alt="">
    <h3>Date Found: <span><%= @animal.date_found %></span></h3>
    <h3>Location Found: <span><%= @animal.location_found %></span></h3>
    <h3>Current Location: <span><%= @animal.location_current %></span></h3>
    <p class="lat"><%= @animal.lat %></p>
    <p class="long"><%= @animal.long %></p>
    <h3 id="user_location"></h3>
    <h3>Health Status: <span><%= @animal.health_status.capitalize %></span></h3>
    <%= link_to "Contact: #{@animal.user.name}", "/users/profile/#{@animal.user.id}", class: 'link-btn show' %>
    <% if @animal.user.id == session[:user_id] %>
      <a href="<%= edit_found_animal_path(@animal) %>" class="link-btn show">Edit Animal</a>
    <% end %>
  </div>
</div>