config/routes.rb
Rails.application.routes.draw do
  root "incidents#index"

  resources :found_animals, except: [:destroy]
  resources :lost_animals
  resources :users
  resources :incidents
  
  get '/login', to: 'session#new'
  delete 'incidents/:id', to: 'incidents#destroy'
  post 'session', to: 'session#create'
  delete 'session', to: 'session#destroy'
  get 'users/profile/:id', to: 'users#profile'

  namespace 'api' do
    resources :found_animals
    resources :lost_animals
    resources :users
  end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emergency Animal Finder - Helping to re-unite lost animals during emergency incidents</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:100,300i,400,700,900|Open+Sans:300,400,700|Raleway:100,400,700,900', media: 'all' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <nav>
    <a href="/" class="home-btn"><h1>EAF</h1></a>
    <div class="nav-links">
      <%= link_to 'Incidents', incidents_path %>
      <%= link_to 'Lost an Animal?', new_lost_animal_path %>
      <%= link_to 'Found an Animal?', new_found_animal_path %>
      <% if @current_user && @current_user.admin_privilege %>
        <%= link_to 'Add Incident', new_incident_path %>
      <% end %>
    </div> 
    <div class="user-links">
      <% @current_user = User.find_by(id: session[:user_id])%>
      <% if @current_user %>
          <%= link_to "#{@current_user.name}", "/users/#{@current_user.name}"%>
          <%= link_to "Log out", session_path, method: "delete" %>
        <% else %>
          <%= link_to 'Register', new_user_path %>
          <%= link_to 'Sign In', login_path %>
      <% end %>
    </div> 
  </nav>

  <body>
    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
  
    
    <%= yield %>
  </body>
  <%= javascript_include_tag 'application' %>
</html>